### ISSUE TITLE
Binaries can only be pulled via HTTP

### ISSUE THREAD

**Issue by niklas88** [enclustra-bsp/enclustra-buildscripts#2]
Hello all,

so I was wondering about the preferred way of handling custom bitstream/FSBL binaries. The binary sections only allow specifying a URL and due to a wget limitation this only works for HTTP/S and possibly FTP URLs but not for local files or a git repository. Also just locally replacing them in the binaries folder doesn't work because they will always be overwritten unlike changes to the local source repositories. So I was wondering what the intended workflow looks like.

**Comment by tgorochowik** [comment]
Hello Niklas,

We've decided to replace wget with cUrl, to make work with local files easier.
cUrl does support the file:// scheme.

The changes have been pushed to the 1.3 branch (https://github.com/enclustra-bsp/bsp-xilinx/tree/1.3-develop).

If you want to work on the master branch, you might want to use a quick workaround and run a local http server for serving the files, e.g. `# python2 -m SimpleHTTPServer 80` serves the current directory.

Note that root privileges are required in order to run it on port 80.

Hope this helps.

**Comment by niklas88** [comment]
Hello Tomasz,

thanks, this is great! Also wow what a turnaround time.
